appchallenges/urls.py
from django.urls import path

from .views import monthly_challenges, monthly_challenge_by_number, index

app_name = "appchallenges"

urlpatterns = [
    path("", index, name="index"),
    path("<int:month>/", monthly_challenge_by_number),
    path("<str:month>/", monthly_challenges, name="challengemonth"),
]

webpages/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("challenges/", include("appchallenges.urls")),
    path("admin/", admin.site.urls),
]

appchallenges/models.py
from django.db import models

# Create your models here.

appchallenges/views.py
from django.shortcuts import render  # noqa: F401
from django.urls import reverse
from django.http import HttpResponseNotFound, HttpResponseRedirect, Http404

 
monthly_chall = {
    "january": "Eat many meat and drink much beer!",
    "february": "Walk for at least 20 minutes every day!",
    "march": "Hard learn Django Framework!",
    "april": "Hard learn Django Framework!",
    "may": "Eat many meat and drink much beer!",
    "june": "Walk for at least 20 minutes every day!",
    "july": "Hard learn Django Framework!",
    "august": "Eat many meat and drink much beer!",
    "september": "Walk for at least 20 minutes every day!",
    "october": "Hard learn Django Framework!",
    "november": "Eat many meat and drink much beer!",
    "december": "Walk for at least 20 minutes every day!",
}

def index(request):
    months = list(monthly_chall.keys())
    
    return render(request, "appchallenges/index.html", {
        "months": months
    })


def monthly_challenge_by_number(request, month):
    months = list(monthly_chall.keys())

    if month > len(months):
        return HttpResponseNotFound("Invalid month")
    
    forward_month = months[month - 1]
    """
    В функции reverse обязательно перед наименованием маршрута указывать имя приложения!
    Например, как в данном случае - "appchallenges:challengemonth"
    """
    redirect_path = reverse("appchallenges:challengemonth", args=(forward_month,))
    return HttpResponseRedirect(redirect_path)


def monthly_challenges(request, month):
    try:
        challenge_text = monthly_chall[month]
        return render(request, "appchallenges/challenge.html", {
            "text": challenge_text,
            "month_name": month
        })
        
    except:  # noqa: E722
        raise Http404()
    

appchallenges/templates/appchallenges/challenge.html
{% extends 'base.html' %}
{% block title %}
{{ month_name|title }} Challenge
{% endblock title %}

{% block content %}
<h1>This {{ month_name|title }} Challenge</h1>
{% if text is not None %}
<h2>{{ text }}</h2>
{% else %}
<p>There is no challenge for this month yet!</p>
{% endif %}
{% endblock content %}

appchallenges/templates/appchallenges/includes/header.html
<header>
    <nav>
        <a href="{% url 'appchallenges:index' %}">All Challenges</a>
    </nav>
</header>

appchallenges/templates/appchallenges/index.html
{% extends 'base.html' %}

{% block title %}
All challenges
{% endblock title %}

{% block content %}

<ul>
        {% for month in months %}
        <li><a href="{% url 'appchallenges:challengemonth' month %}">{{ month|title }}</a></li>
        {% endfor %}
    </ul>
{% endblock content %}    
    

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock title %}</title>
</head>
<body>
    {% include "appchallenges/includes/header.html" %}
    {% block content %}
    
    {% endblock content %}

    
    
</body>
</html>